baseURL = "https://lghs.be/"
languageCode = "fr-be"
title = "Liège Hackerspace"
theme = "LHGS21"
relativeURLS = true

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
